[source]
type = "N2N"
address = "relays-new.cardano-mainnet.iohk.io:3001"

[[reducers]]
type = "UtxoByAddress"
key_prefix = "c1"

[[reducers]]
type = "PointByTx"
key_prefix = "c2"

[[reducers]]
type = "PoolByStake"
key_prefix = "c3"

[[reducers]]
type = "PlutusScriptByHash"
key_prefix = "c4"

[storage]
type = "Redis"
connection_params = "redis://localhost:6379"

[intersect]
type = "Tip"

[chain]
type = "Mainnet"
